# Generated by Django 3.2.1 on 2021-05-06 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='code',
            field=models.CharField(default='', max_length=6),
            preserve_default=False,
        ),
    ]
