# Generated by Django 3.2.4 on 2021-07-27 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='project',
        ),
    ]
