# Generated by Django 3.2.3 on 2021-07-13 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default='logo.jpg', upload_to='projects/'),
        ),
    ]
