# Generated by Django 3.2.3 on 2021-07-13 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditure',
            name='reason',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
