# Generated by Django 3.2.4 on 2021-08-14 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_expenditure_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
