# Generated by Django 3.2.1 on 2021-05-19 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_expenditure_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditure',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.project'),
        ),
        migrations.AddField(
            model_name='income',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.project'),
        ),
    ]
