# Generated by Django 3.2.3 on 2021-07-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_inventory_reference_copy'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='chassis',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='registration_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
