# Generated by Django 3.2.4 on 2021-08-15 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_asset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='staff',
            new_name='added_by',
        ),
        migrations.AddField(
            model_name='asset',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='sold_to',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
