# Generated by Django 3.2.3 on 2021-07-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_auto_20210714_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='place.jpg', upload_to='projects/'),
        ),
    ]
