# Generated by Django 3.2.4 on 2021-08-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0011_auto_20210823_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='paid_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
