# Generated by Django 3.2.4 on 2021-08-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0012_salary_paid_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salary',
            old_name='amount',
            new_name='amount_paid',
        ),
        migrations.AddField(
            model_name='salary',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salary',
            name='expected_amount',
            field=models.IntegerField(default=0),
        ),
    ]
