# Generated by Django 3.2.4 on 2021-08-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0015_alter_asset_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='cost',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
