# Generated by Django 3.2.4 on 2021-08-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0017_alter_asset_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
